frontend/src/App.jsx, frontend/src/components/UserForm.jsx, frontend/src/components/UserForm/UserForm.jsx, frontend/src/store/temporaryfile.txt, frontend/src/styles/App.css, frontend/src/styles/index.css
Refactor add folders structure and sketch of UserForm
=> Directories

frontend/.eslintrc.cjs, frontend/package.json, frontend/src/App.jsx, frontend/src/components/UserForm/UserForm.jsx, frontend/src/components/UserForm/UserForm.test.js
El propósito de esta rama era intentar hacer pequeños test de el render del formulario de registrar usuario con jest para empezar a testear el front pero hace rato que tanto yo como el resto del equipo de frontend estamos muy trabados con el testing porque estamos teniendo muchos problemas de configuración y del entorno 
en mi caso en particular  al correr 
$ npm test
recibo el error 
console.error
>     Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
>     1. You might have mismatching versions of React and the renderer (such as React DOM)
>     2. You might be breaking the Rules of Hooks
>     3. You might have more than one copy of React in the same app
>     See …
=> Testing set up

frontend/.eslintrc.cjs, frontend/package.json, frontend/src/appActions.js, frontend/src/appActions.test.js, frontend/src/main.jsx, frontend/src/playerSlice.js, frontend/src/playerSlice.test.js, frontend/src/store/store.js
La estructura de Redux con reduxjs/toolkit.
En store guardo los distintos estados que vamos a manejar en la app.
En playerSlice los reducers (funcionalidad) que se tiene para cada la entidad player (en este caso setear nombre)
En appActions guardo la forma en que voy a llamar a los reducers. Notar que tiene tipo player/setName y de payload el nombre que se envie
=> feat: Structure for Redux storage

frontend/.eslintrc.cjs, frontend/.gitignore, frontend/package.json, frontend/src/appActions.js, frontend/src/appActions.test.js, frontend/src/main.jsx, frontend/src/playerSlice.js, frontend/src/playerSlice.test.js, frontend/src/sendPlayerName.jsx, frontend/src/store/store.js
Este modulo agrega la llamada al servidor, se debe pasar como argumento un objeto de tipo player que solo contenga el nombre, y recibe un objeto player con nombre y id
=> Send player name

frontend/src/App.jsx, frontend/src/components/UserForm/UserForm.jsx, frontend/src/playerSlice.test.js, frontend/src/sendPlayerName.jsx, frontend/src/store/store.js
Unimos la logica de formik con las acciones de redux (made by @TomasBazan ) para completar la funcionalidad de registrar el nombre de usuario 
¿que cambio?
ahora nuestro boton onsubmit utiliza estados de redux tanto  para manejar el estado del usuario en el front guardando el username como para enviar un http request al back para registrar el nombre de usuario en la base de datos y devolver el id con el cual se lo registro al usuario
jira tickets : LCVW-43 and  LCVW-45
=> User form logic

frontend/src/components/CreateGameForm/CreateGameForm.jsx, frontend/src/components/UserForm/UserForm.jsx, frontend/src/components/request/sendPlayerName.mock.jsx, frontend/src/playerSlice.js, frontend/src/store/store.js
Formulario para crear partida utilizando el estado del id de usuario guardado en UserForm
=> Create game form

frontend/src/components/request/sendPlayerName.jsx
Cambie el codigo de SendPlayerName para que sea consistente con las otras llamadas a la api
=> Jira: LCVW-22 refactor: refactor of sendPlayer

frontend/README.md, frontend/src/components/UserForm/UserForm.jsx, frontend/src/components/UserForm/UserForm.test.jsx, frontend/src/components/request/sendPlayerName.jsx
La llamada con el backend esta funcionando
=> Conextion game

frontend/README.md, frontend/src/components/CreateGameForm/CreateGameForm.jsx, frontend/src/components/UserForm/UserForm.jsx, frontend/src/components/request/createGame.jsx, frontend/src/components/request/playCard.jsx, frontend/src/components/request/sendPlayerName.jsx, frontend/src/components/request/startGame.jsx, frontend/src/main.jsx
Refactor gral y limpieza de codigo de sendPlayer, createGame, UserForm y CreateGameForm. Agregada documentacion de respuestas de los modulos de request
=> Lcvw 52 requests front back

frontend/src/components/request/joinGame.jsx
Refactor de funcion joinGame acomodando el formato devuelto para que sea consistente con la documentacion
=> Refactor: refactor joinGame function with values documented

frontend/src/components/request/getLobyStatus.jsx
Agregada la request para obtener el status del loby
=> feat: add the getLobyStatus

frontend/package.json, frontend/src/App.jsx, frontend/src/components/Lobby/Lobby.jsx
Primera version del lobby para que el resto pueda testear y conectar sus componentes
=> feat lobby initial

frontend/src/App.jsx, frontend/src/components/Card/Card.jsx, frontend/src/components/Game/Game.css, frontend/src/components/Game/Game.jsx, frontend/src/main.jsx
Cambié la ubicación de Game.jsx de src a src/components/Game/. El routing se rompía con src/Game.jsx porque ese se usaba como entry point para testear la interfaz del juego, y creaba el DOM en vez de incorporar un componente al DOM, ahora Game es simplemente un componente que incluye a Deck y Hand.
Actualicé el path al archivo con las definiciones del msw worker. Para que ande Game hay que habilitar msw descomentando las líneas 8 y 9 (import y start) para mockear las responses, si no no se cargan las cartas.
Arreglé el path hacia las imagenes, en vez de usar un path relativo se usa uno absoluto, porque si no cuando se hace el routing se rompe.
=> Add route to Game component in App.jsx

frontend/src/appActions.js, frontend/src/components/FinishGame/Footer.jsx, frontend/src/components/FinishGame/GameHistory.jsx, frontend/src/components/UserForm/UserForm.jsx, frontend/src/containers/FinishGame.jsx, frontend/src/playerSlice.js
Componente que muestra los resultado y redirecciona al Home page. Echo con chakra-ui. Falta realizar el handeling para que no sea necesario volver a ingresar un nombre
=> LCVW-31-feat: finish game layout

frontend/src/components/Deck/Deck.jsx, frontend/src/components/Hand/Hand.jsx, frontend/src/mocks/handlers.js
Modularicé las http requests usando las funciones provistas en src/components/request (resuelve el comentario de mili en la pr #17). Actualicé los paths de los msw handlers para que coincidan con los usados en estas funciones.
Saqué datos que estaban mockeados y una request que no correspondía.
=> refactor Hand and Deck, solved comment on pr #17 

frontend/src/components/request/createGame.jsx, frontend/src/components/request/getCard.jsx, frontend/src/components/request/getGameStatus.jsx, frontend/src/components/request/getHand.jsx, frontend/src/components/request/getLobyStatus.jsx, frontend/src/components/request/playCard.jsx, frontend/src/components/request/sendPlayerName.jsx, frontend/src/components/request/startGame.jsx
Cambiado todos los request al back para coincidir con el server
=> Refactor: change all request to match the fields of the backend

frontend/src/App.jsx, frontend/src/components/CreateGameForm/CreateGameForm.jsx, frontend/src/components/ListarPartidas/ListarPartidas.jsx, frontend/src/components/request/joinGame.jsx
añadi el put en la base de datos al unirse a la partida y que cuando un usuario crea una partida es redireccionado al lobby de esa partida por ahora Partida-Inicial
=> Unirse a partida bdd

frontend/src/appActions.js, frontend/src/components/Lobby/Lobby.jsx
=> Fix versiones del lobby

frontend/src/components/CreateGameForm/CreateGameForm.jsx, frontend/src/components/ListarPartidas/ListarPartidas.jsx, frontend/src/components/Lobby/Lobby.jsx, frontend/src/components/UserForm/UserForm.jsx
Solo cambie los returns de las funciones que renderean componentes para que se vean mas lindas con chackra
=> feat change the syle of the components to render right with Charka iu

frontend/package.json, frontend/src/appActions.js, frontend/src/components/FinishGame/Footer.jsx, frontend/src/components/FinishGame/GameHistory.jsx, frontend/src/components/FinishGame/GameHistory.test.jsx, frontend/src/components/request/getGameStatus.jsx, frontend/src/containers/FinishGame.jsx, frontend/src/containers/FinishGame.test.jsx, frontend/src/services/gameSlice.js, frontend/src/services/providerForTest/utils-for-tests.jsx
Se modificaron el componente Finish Game para que sea un componente que se llame una vez que la partida termina. 
Se cambio los el estado de gameSlice de rol a isFinish (por default esta en uno que significa que esta comenzada, 2 significa terminada). Tambien se modifico la action.
GameHistory no tiene una prop como parametro, ahora checkea el valor mediante redux. Se cambia como se consulta ese valor y algunos styles. Se elimina el checker de props.
Se cambia la funcion que llama al back para que tome el game_status y no el rol.
FinishGame solo toma como prop el id del jugador de la actual session:
En Footer se elimina comentario.
=> feat: Integration of the Game with FinishGame

frontend/src/components/Game/Game.css, frontend/src/components/Game/Game.jsx, frontend/src/components/Hand/Hand.css, frontend/src/components/Hand/Hand.jsx
Elimine los .css y modifique Hand para que las cartas no se agranden a medida que queden menos. Arregle un error en Game de una action que habia quedado vieja
=> style: cards position fixed

frontend/src/components/Game/Game.jsx
Agregado que el finishTurn solo se ejecute si el id del jugador que toco el boton sea el mismo que tenga el turno
=> feat: add conditional finish turn

frontend/src/components/Lobby/Lobby.jsx
Agrege un boton de abandonar partida al lobby que envia al back la request necesaria
si quien abandona la partida es el host se redirecciona a todos los jugadores a la lista de partidas disponibles
=> feat: abandonar partida desde el lobby

frontend/src/components/CreateGameForm/CreateGameForm.jsx
agrege un campo en el user form para que se pida el maximo de jugadores en la partida, este campo debe estar entre 4 y 12, 
al listar partidas este numero maximo de jugadores se ve correctamente en cada partida
=> feat add the max_players and min_players fields for the user to choose

frontend/src/appActions.js, frontend/src/components/Deck/Deck.jsx, frontend/src/components/DiscardPile/DiscardPile.jsx, frontend/src/components/Game/Game.jsx, frontend/src/components/PlayArea/PlayArea.jsx, frontend/src/services/handSlice.js
Antes de levantar, descartar o jugar una carta se chequea que el jugador tenga permitidas esas acciones
=> Check turn conditions before letting players perform actions

frontend/src/components/UserForm/UserForm.test.js, frontend/src/services/providerForTest/utils-for-tests.jsx
Modificado el utils-for-testing para que no use el playerSlice
Se agrega un mock para las session storage
=> fix: fix tests for UserForm

frontend/src/components/ListarPartidas/ListarPartidas.jsx, frontend/src/components/ListarPartidas/ListarPartidas.test.js, frontend/src/components/request/getGameList.jsx
Se testea
* que las partidas se muestren en la pantalla 
* que cuando no hay partidas se le avise al usuario
* que al usar el boton de unirse se envie la request adecuada al back 
* que se haga handeling de los pedidos del back en caso de error
Una vez mas tuve que modificar que los errores se muestren en pantalla y no en alertas para que jest pueda testearlo
=> test funcionalidades del componenete listar partidas

frontend/src/components/Lobby/Lobby.jsx, frontend/src/components/Lobby/Lobby.test.js
Añadi test que chequean todas las respuestas del back que dan estatus ok y las que dan error tambien
ademas testeo que la lista de jugadores se esta mostrando correctamente y que los botones se puedan usar en los momentos que deberian
igual que con los otros componentes cambie las alertas de pop up por un texto que se renderea en pantalla para que jest me deje ver los mensajes
=> test for Lobby component

frontend/src/components/Game/PlayerIcons.jsx, frontend/src/components/Game/PlayerIcons.test.jsx, frontend/src/components/Hand/Hand.jsx, frontend/src/containers/FinishGame.test.jsx
Arreglado test de FinishGame, Game y PlayerIcons
=> Lcvw 148 fix tests front

frontend/src/components/Game/Positions.jsx, frontend/src/customHooks/usePlayers.js
* Folder para customHooks 
* usePlayers customHook para manejar la informacion de los jugadores y el turno actual
* Funciones que manejaban estos datos dentro de Positions.jsx
=> refactor: add customHook for handeling of the Players data in Positions

frontend/src/components/Card/Card.test.jsx, frontend/src/customHooks/usePlayers.js
* Fix import route de useSelector en el usePlayers.js
* Fix de como busco el alt text de card
=> fix: fix test Card and fix import route of customHook

frontend/src/components/Game/Game.test.jsx, frontend/src/components/Game/PlayerIcons.jsx, frontend/src/components/Game/Positions.jsx, frontend/src/components/Game/Positions.test.jsx
* Ahora los players se muestran distribuidos alrededor de la mesa y no se apilan desde abajo
=> Lcvw 150 refactor disposicion de players

frontend/README.md, frontend/mockWs/mockServer.js, frontend/src/__mocks__/WebSockets.js, frontend/src/components/Game/Chat.jsx, frontend/src/components/Game/Chat.test.jsx, frontend/src/components/Game/Game.jsx
unas respuestas basicas para el chat, y una respuesta de getGameStatus que tenia de antes, puede que este obsoleta o le falten cosas
todo lo que tenga que ver con play card y mandar despues de jugar
```node mockServer.js```
Se puede ver las conecciones, tambien se puede hacer console.log dentro del mock para ver que se recibe en el back
=> Mock server ws

frontend/src/__mocks__/WebSockets.js, frontend/src/components/Game/Chat.jsx, frontend/src/components/Game/Chat.test.jsx, frontend/src/components/Game/Game.jsx
* Se ve el chat en todo momento al lado de la area de juego (jugadores,cartas,mesa)
* Tiene un boton para enviar que se activa con enter o apretando el boton
* Tiene una casilla para escribir los mensajes
* Tiene un box para ver los mensjes recibidos
* Una vez escrito el mensje y enviado se envia mediante la coneccion el mensaje al back
* En useEffect se checkea los mensajes entrantes para poder setear el estado del chat y mostrarlo
* Primer test basico para ver los componentes
* Segundo test para checkear que se puede enviar mensajes y que los vean (Hay un problema con useState, cuando mando un mensaje me pisa el anterior aunque tenga la concatenacion del estado previo)
* Tercer test para checkear que los mensajes los puedan ver ambos jugadores.
=> Lcvw 125 chat durante la partida frontend

frontend/src/components/Game/Game.jsx, frontend/src/components/request/getGameStatus.jsx
Que cambia ? 
Usamos una conexion de WS para fetchear el getGameStatus
warning los test de game fallan
=> Lcvw 147 agregar websockets al aplicar efecto en el frontend

frontend/src/components/Hand/Hand.test.jsx
**Necesita de la pull request #91** 
Testea interacciones de redux
=> Lcvw 152 testing hand

frontend/src/components/PlayArea/PlayArea.test.jsx, frontend/src/components/PlayArea/mockStore.js
**Necesita de la pull request #91** 
Se implementan los casos de test especificados como criterios de aceptación y algunos más.
=> feat: implement tests for PlayArea component

frontend/src/components/Game/Chat.jsx, frontend/src/components/Game/Game.jsx, frontend/src/components/PlayArea/PlayArea.jsx, frontend/src/main.jsx
Add fixes to the Chat to handle correctly the connection
=> merge: main to fixes fo the chat

frontend/package.json, frontend/src/appActions.js, frontend/src/components/Defense/Defense.jsx, frontend/src/components/Defense/Defense.test.jsx, frontend/src/components/Game/Game.jsx, frontend/src/components/Game/PlayerIcons.jsx, frontend/src/components/Hand/Hand.jsx, frontend/src/components/PlayArea/PlayArea.jsx, frontend/src/components/request/getGameStatus.jsx, frontend/src/services/gameSlice.js, frontend/src/services/playAreaSlice.js, frontend/src/services/providerForTest/utils-for-tests.jsx
Display
modal que muestra las cartas disponibles de defensa para el ataque que me hicieron y da la posibiliadad de defenderse o no
Tiene un boton para enviar la defensa
Tiene una boton para cerrar sin defenderse
Funcionamientos
Se utilizan conexiones de ws sockets
si un usuario es atacado se entera por esta conexion si es que tiene cartas de defensa, en ese caso se le permite jugar solo las cartas con las que se puede defender
=> Lcvw 157 crear logica de defensa del front end

frontend/src/components/Defense/Defense.test.jsx
=> fix test defense

frontend/src/appActions.js, frontend/src/components/Deck/Deck.jsx, frontend/src/components/Lobby/Lobby.jsx, frontend/src/components/request/getDeckTopCard.jsx, frontend/src/services/gameSlice.js
Resuelve el bug de que la primera carta del mazo se renderea sólo para el jugador que inicia la partida
=> Lcvw 163 fix deck top card

frontend/src/components/Game/Game.test.jsx
=> fix Game test
